version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: social-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-post:
    image: postgres:16
    container_name: postgres-post

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_POST_DB}
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5434:5432"

    volumes:
      - postgres_post_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: social-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  redis:
    image: redis:7
    container_name: social-redis

    ports:
      - "6379:6379"

    restart: always

  seq:
    image: datalust/seq:latest
    container_name: social-seq

    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_FIRSTRUN_ADMINPASSWORD}

    ports:
      - "5341:80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: social-elasticsearch

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - "9200:9200"
      - "9300:9300"

    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: social-kibana

    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

    ports:
      - "5601:5601"

    depends_on:
      - elasticsearch

  post-service:
    build:
      context: ../../services/post-service/src
      dockerfile: PostService.Api/Dockerfile
    container_name: post-service
    ports:
      - "5001:8080"
    depends_on:
      - postgres
      - rabbitmq

  search-service:
    build:
      context: ../../services/search-service/src
      dockerfile: SearchService.Api/Dockerfile
    container_name: search-service
    ports:
      - "5002:8080"
    depends_on:
      - rabbitmq
      - elasticsearch

  api-gateway:
    build:
      context: ../../gateway/ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "5000:8080"
    depends_on:
      - post-service
      - search-service
volumes:
  postgres_data:
  postgres_post_data:
  es_data:
